CONFIG_LOG=y
CONFIG_LOG_MODE_IMMEDIATE=y
CONFIG_LOG_DEFAULT_LEVEL=3
# CONFIG_LOG_BACKEND_SHOW_TIMESTAMP=y
# CONFIG_LOG_BACKEND_FORMAT_TIMESTAMP=y
# CONFIG_LOG_OUTPUT_FORMAT_TIME_TIMESTAMP=y

CONFIG_BUILD_OUTPUT_HEX=y

CONFIG_GPIO=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_SERIAL=y
CONFIG_ARM_MPU=y
CONFIG_HW_STACK_PROTECTION=y
# CONFIG_ICACHE=y
# CONFIG_DCACHE=y
# CONFIG_CACHE=y

CONFIG_DEVICE_CONFIGURATION_DATA=y
CONFIG_NXP_IMX_EXTERNAL_SDRAM=y

CONFIG_WATCHDOG=y
CONFIG_BOOT_WATCHDOG_FEED=y
CONFIG_WDT_MCUX_IMX_WDOG=y
CONFIG_WDT_LOG_LEVEL_DBG=y

CONFIG_BOOT_SIGNATURE_KEY_FILE="../../vestfrost-level3-imx-app/keys/root-rsa-2048-prod.pem"
CONFIG_BOOT_RAM_LOAD=y
CONFIG_BOOT_INTR_VEC_RELOC=y
CONFIG_BOOT_IMAGE_EXECUTABLE_RAM_START=0x80000000
CONFIG_BOOT_IMAGE_EXECUTABLE_RAM_SIZE=4194304

CONFIG_USE_DT_CODE_PARTITION=y

CONFIG_CDC_ACM_SERIAL_INITIALIZE_AT_BOOT=n

# Scheduling: don't let UDC starve the system
CONFIG_UDC_WORKQUEUE_PRIORITY=1
CONFIG_UDC_WORKQUEUE_STACK_SIZE=4096
CONFIG_UDC_BUF_COUNT=32
CONFIG_UDC_BUF_POOL_SIZE=4096

# USB device stack
CONFIG_USB_DEVICE_STACK_NEXT=y

# Deeper USBD message pipeline
CONFIG_USBD_MAX_UDC_MSG=32
CONFIG_USBD_MSG_SLAB_COUNT=32
CONFIG_USBD_THREAD_STACK_SIZE=4096

# USB MSC class
CONFIG_USBD_MSC_CLASS=y
CONFIG_USBD_MSC_STACK_SIZE=4096
CONFIG_USBD_MSC_THREAD_PRIORITY=10
CONFIG_USBD_MSC_LUNS_PER_INSTANCE=1
CONFIG_USBD_MSC_SCSI_BUFFER_SIZE=61440

# USB MSC extras
CONFIG_DISK_ACCESS=y
CONFIG_DISK_DRIVERS=y
CONFIG_FILE_SYSTEM=y
CONFIG_FILE_SYSTEM_MKFS=y
CONFIG_FAT_FILESYSTEM_ELM=y
CONFIG_FS_FATFS_EXTRA_NATIVE_API=y
CONFIG_FS_FATFS_MAX_SS=4096
CONFIG_FS_FATFS_WINDOW_ALIGNMENT=4096
CONFIG_FS_FATFS_MKFS=y

CONFIG_FLASHDISK_BLOCK_ERASE=y
CONFIG_FLASHDISK_BLOCK_ERASE_SIZE=65536
CONFIG_FLASHDISK_BLOCK_ERASE_MINIMUM_PAGES=5
CONFIG_FLASHDISK_VERIFY_PAGE_LAYOUT=y

CONFIG_STREAM_FLASH=y
CONFIG_IMG_ERASE_PROGRESSIVELY=y
CONFIG_STREAM_FLASH_ERASE=y

CONFIG_IMG_MANAGER=y
CONFIG_IMG_BLOCK_BUF_SIZE=4096
CONFIG_MCUBOOT_IMG_MANAGER=y

CONFIG_MCUBOOT_ACTION_HOOKS=y
CONFIG_MCUBOOT_CLEANUP_RAM=y
CONFIG_BOOT_GO_HOOKS=y

# Flash access for shared data
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_CRC=y

# Parrot-bootstate Application-MCUBoot interface
CONFIG_LIB_PARROT_BOOTSTATE=y

# Logging levels
CONFIG_UDC_DRIVER_LOG_LEVEL_WRN=y
CONFIG_USBD_LOG_LEVEL_WRN=y
CONFIG_USBD_MSC_LOG_LEVEL_WRN=y
CONFIG_DISK_LOG_LEVEL_WRN=y
CONFIG_FLASHDISK_LOG_LEVEL_WRN=y

CONFIG_PM=n

CONFIG_MAIN_STACK_SIZE=20480

CONFIG_BOOT_SWAP_SAVE_ENCTLV=n
CONFIG_BOOT_ENCRYPT_IMAGE=n
CONFIG_BOOT_UPGRADE_ONLY=n
CONFIG_BOOT_BOOTSTRAP=n

### mbedTLS has its own heap
# CONFIG_HEAP_MEM_POOL_SIZE is not set

### Use info log level by default
CONFIG_MCUBOOT_LOG_LEVEL_INF=y
### Decrease footprint by ~4 KB in comparison to CBPRINTF_COMPLETE=y
CONFIG_CBPRINTF_NANO=y
### Use picolibc to reduce flash usage
CONFIG_PICOLIBC=y
### Disable malloc arena because we don't need it
CONFIG_COMMON_LIBC_MALLOC_ARENA_SIZE=0
